---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
        * Incredibly awesome content
    media:
      - ebooks
    price: 3500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        * Includes 10 hours of video screencasts
        * Ebooks inclded in PDF/EPUB/MOBI formats
    media:
      - ebooks
      - media/screencasts
    price: 12500

authors:
  -
    name: "Rahul Lakhaney"
    image: /images/avatar.png
    contact_email: "rahul.lakhaney@gmail.com"
    contact_twitter: "@istereotype"
    contact_fb: "http://facebook.com/lakhaney"
    contact_gh: "@istereotype"
    bio:
      |
        Author bio [link](https://www.rahullakhaney.me)


marketing_content: ''

repo_url: ''
contact_email: 'rahul.lakhaney@gmail.com'
hide_custom_domain_footer: true
